### ISSUE TITLE
Mobs losing the ability to swim with mod enabled

### ISSUE THREAD

**Issue by Luigipunch** [Corosauce/mobtimizations#1]
I'm not sure if it was solely this mod or some wierd conflict but land-based mobs seem to lose the ability to swim in water, sinking as fast as falling through water

**Comment by Luigipunch** [comment]
The issues stop with optimizationMobWandering disabled, so it's seemingly an issue with that feature.

**Comment by Corosauce** [comment]
Without more specifics I can't seem to reproduce, husks, zombies, skeletons, all sink in vanilla. Spiders, witch, etc still float with the mod installed.
